"use client";

import { useAtlas } from "../store";
import { Box } from "../ui";
import { exportDeck } from "@/lib/atlas/export";

const COLS = "1.6fr 1.2fr 0.8fr 0.7fr 1.6fr 1fr 0.7fr";

export function ReportsScreen() {
  const a = useAtlas();
  return (
    <section style={{ padding: "30px 34px 60px", maxWidth: 1080, margin: "0 auto", animation: "fadeUp .35s ease both" }}>
      <div style={{ marginBottom: 22 }}>
        <h1 style={{ margin: 0, fontSize: 27, fontWeight: 800, letterSpacing: "-.02em", color: "#1d1b2e" }}>Reports</h1>
      </div>

      <div style={{ background: "#fff", border: "1px solid #e8e8ef", borderRadius: 16, overflow: "hidden", boxShadow: "0 1px 3px rgba(20,18,31,.04)" }}>
        <div style={{ display: "grid", gridTemplateColumns: COLS, gap: 12, padding: "13px 22px", background: "#fafafc", borderBottom: "1px solid #e8e8ef", fontSize: 11, fontWeight: 800, letterSpacing: ".05em", textTransform: "uppercase", color: "#92929d" }}>
          <span>Report</span><span>Generated by</span><span>Export</span><span>Time</span><span>Shared with</span><span>Created</span><span style={{ textAlign: "right" }}>Deck</span>
        </div>
        {a.reports.map((r) => {
          const csInitials = r.generatedBy.split(/\s+/).slice(0, 2).map((w) => w[0]).join("").toUpperCase();
          const isEmail = r.channel === "Email";
          const hasRec = r.recipients.length > 0;
          const recLabel = hasRec ? (r.recipients[0] + (r.recipients.length > 1 ? ` +${r.recipients.length - 1}` : "")) : "";
          const downloaded = a.downloadedId === r.id;
          return (
            <div key={r.id} style={{ display: "grid", gridTemplateColumns: COLS, gap: 12, padding: "15px 22px", borderBottom: "1px solid #f0f0f4", alignItems: "center" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 11, minWidth: 0 }}>
                <div style={{ width: 34, height: 34, borderRadius: 9, background: r.logoBg, color: r.logoFg, display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 800, fontSize: 12.5, flex: "none" }}>{r.initials}</div>
                <div style={{ minWidth: 0 }}>
                  <div style={{ fontWeight: 700, fontSize: 13.5, color: "#1d1b2e", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{r.brand}</div>
                  <div style={{ fontSize: 11.5, color: "#86868f" }}>{r.period}</div>
                </div>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: 8, minWidth: 0 }}>
                <span style={{ width: 26, height: 26, borderRadius: "50%", background: "linear-gradient(135deg,#6b63f7,#4a43d6)", color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 10, fontWeight: 800, flex: "none" }}>{csInitials}</span>
                <span style={{ fontSize: 13, color: "#3a3654", fontWeight: 600, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{r.generatedBy}</span>
              </div>
              <span>
                <span style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 11, fontWeight: 800, color: isEmail ? "#1f5fd0" : "#5b5775", background: isEmail ? "#eaf1fe" : "#f0f0f4", padding: "4px 10px", borderRadius: 999, whiteSpace: "nowrap" }}>
                  {isEmail ? (
                    <><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="5" width="18" height="14" rx="2" /><path d="M3 7l9 6 9-6" /></svg>Email</>
                  ) : (
                    <><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 4 5-4M5 20h14" /></svg>Download</>
                  )}
                </span>
              </span>
              <span style={{ fontSize: 13, fontWeight: 700, color: "#3a3654" }}>{r.timeTaken}</span>
              <div style={{ display: "flex", alignItems: "center", gap: 8, minWidth: 0 }} title={r.recipients.join(", ")}>
                {hasRec ? (
                  <>
                    <span style={{ width: 24, height: 24, borderRadius: "50%", background: "#eef0f3", color: "#5c5c68", display: "flex", alignItems: "center", justifyContent: "center", flex: "none" }}>
                      <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="8" r="3.4" /><path d="M5 20a7 7 0 0 1 14 0" /></svg>
                    </span>
                    <span style={{ fontSize: 13, color: "#3a3654", fontWeight: 600, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{recLabel}</span>
                  </>
                ) : (
                  <span style={{ fontSize: 12.5, color: "#a3a3ad", fontWeight: 600, fontStyle: "italic" }}>Not shared · download only</span>
                )}
              </div>
              <span style={{ fontSize: 13, color: "#5f5f6b", fontWeight: 600 }}>{r.sharedOn}</span>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "flex-end" }}>
                <Box as="button" s="display:inline-flex;align-items:center;gap:6px;background:#fff;color:#5b5775;border:1px solid #e6e3f2;border-radius:8px;padding:7px 11px;font-size:12px;font-weight:700;cursor:pointer;font-family:inherit;white-space:nowrap" h="background:#f5f3fe;border:1px solid #d8d2f3" onClick={() => { exportDeck(r.brand, a.reportSpec).catch(console.error); a.downloadReport(r.id); }} title="Download .pptx">
                  {downloaded ? (
                    <span style={{ display: "inline-flex", alignItems: "center", gap: 6, color: "#0f8a52" }}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#0f9a5a" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12l4 4 10-10" /></svg>Saved</span>
                  ) : (
                    <span style={{ display: "inline-flex", alignItems: "center", gap: 6 }}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 4 5-4M5 20h14" /></svg>.pptx</span>
                  )}
                </Box>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
